sudo: false

dist: trusty

cache:
  directories:
    - $HOME/.cache/composer/files

language:
  - php

before_install:
  - phpenv config-rm xdebug.ini || echo 'No xdebug config.'

install:
  - composer require squizlabs/php_codesniffer:"$PHPCS_BRANCH" --update-no-dev --no-suggest --no-scripts
  - composer install --dev --no-suggest

script:
  # Run the unit tests.
  - ./bin/unit-tests

stages:
  - sniff
  - test

jobs:
  allow_failure:
    - php: nightly
  fast_finish: true
  include:

    - stage: test
      php: 7.2
      env: PHPCS_BRANCH="dev-master"

    - stage: test
      php: 7.2
      env: PHPCS_BRANCH="3.2.3"

    # Only use PHPCS_BRANCH="dev-master" from this point.
    - stage: test
      php: nightly
      env: PHPCS_BRANCH="dev-master"